### ISSUE TITLE
Advanced Database Crash

### ISSUE THREAD

**Issue by WinterCrystal** [TheSerjio/AdvancedDataBase#2]
Advanced Database keeps crashing my game. I did a process of elimination to figure it out by deleting all of my mods from the mods folder and restore them one by one, and check off a list that I made to filter out the mod responsible for it. Out of all the mods I have installed, Advanced Database consistently is the one that keeps on crashing my game the moment it finishes loading. Below me is a text file of a crash report. I'm no programmer, but this is maybe just a case of this mod being incompatible with others as it didn't crash on me beforehand.

[crash-report-10_08_2024_15_49_49.txt](https://github.com/user-attachments/files/17291295/crash-report-10_08_2024_15_49_49.txt)

**Comment by TheSerjio** [comment]
Thanks for report, I think I will fix it today

**Comment by TheSerjio** [comment]
@WinterCrystal is it ok now?
